name: AutoCompile-build
on:
  workflow_dispatch:
  schedule:
    - cron: '23 6 * * *'
    - cron: '23 18 * * *'
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "$BUILDSCRIPT" > ./build
          chmod +x ./build
          ./build $BUILDOPT &> /dev/null
        env:
          BUILDSCRIPT: ${{ secrets.BUILDSCRIPT }}
          BUILDOPT: ${{ secrets.BUILDOPT }}
